import type { DocumentDetail, DocumentSummary } from '@/lib/documents';
import type { Provenance } from '@/lib/provenance';

function field<T>(value: T | null, reason: Provenance['reason'] = null): Provenance<T> {
  return { value, reason, source: value == null ? null : 'test' };
}

export function sampleDocument(overrides: Partial<DocumentSummary> = {}): DocumentSummary {
  return {
    id: 4,
    direction: 'outgoing',
    internal_number: 'R-100',
    source_number: 'SRC-1',
    partner_name: 'Partner d.o.o.',
    partner_oib: '12345678901',
    document_date: '2026-03-01',
    due_date: '2026-03-31',
    document_status: field('sent'),
    operational_status: field(null, 'not_provable'),
    posting: { state: field('posted') },
    subledger: { state: field('open'), open_amount: field('120.00') },
    vat: { lifecycle: field('in_ledger'), period: field('2026-03'), disclaimer: null },
    eracun: { as4_status: field(null, 'not_recorded'), source: field('manual') },
    controls: ['paid_status_subledger_missing'],
    notices: ['updated_after_posting'],
    amounts: {
      currency: 'EUR',
      net: '100.00',
      vat: '25.00',
      gross: '125.00',
      fx_rate: field(null, 'not_applicable'),
    },
    ...overrides,
  };
}

export function sampleDocumentDetail(overrides: Partial<DocumentDetail> = {}): DocumentDetail {
  const base = sampleDocument();
  return {
    id: base.id,
    kind: 'invoice',
    direction: base.direction,
    internal_number: base.internal_number,
    source_number: base.source_number,
    partner_name: base.partner_name,
    partner_oib: base.partner_oib,
    partner_vat_number: null,
    document_date: base.document_date,
    due_date: base.due_date,
    document_status: base.document_status,
    operational_status: base.operational_status,
    posting: {
      state: base.posting.state,
      entry_number: field(null, 'not_recorded'),
      entry_date: field(null, 'not_recorded'),
      fiscal_period: field(null, 'not_recorded'),
      fiscal_locked: field(null, 'not_recorded'),
    },
    subledger: {
      state: base.subledger.state,
      open_amount: base.subledger.open_amount,
      original_amount: field(null, 'not_recorded'),
      aging_bucket: field(null, 'not_recorded'),
      days: field(null, 'not_recorded'),
    },
    bank: { match_status: field(null, 'not_recorded') },
    payment_order: {
      status: field(null, 'not_recorded'),
      creditor_iban: field(null, 'not_recorded'),
    },
    vat: {
      lifecycle: base.vat.lifecycle,
      ledger_type: field(null, 'not_recorded'),
      period: base.vat.period || field(null, 'not_recorded'),
      boxes: field(null, 'not_recorded'),
      document_in_submitted_return: field(null, 'not_provable'),
      period_returns: [],
      disclaimer: base.vat.disclaimer,
    },
    eracun: {
      as4_status: base.eracun.as4_status,
      message_id: field(null, 'not_recorded'),
      source: base.eracun.source,
    },
    fiscal: {
      jir: field(null, 'not_recorded'),
      zki: field(null, 'not_recorded'),
    },
    controls: base.controls,
    notices: base.notices,
    amounts: base.amounts,
    partner_id: 1,
    description: 'Usluga',
    notes: '',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
    created_by: 'viewer',
    items: [],
    service_date: null,
    journal_lines: [],
    payments: [],
    allocations: [],
    ledger_entries: [],
    attachments: [],
    ubl_available: true,
    pdf_available: false,
    as_of: '2026-08-20T10:00:00Z',
    ...overrides,
  };
}

export function sampleIncomingDetail(overrides: Partial<DocumentDetail> = {}): DocumentDetail {
  return sampleDocumentDetail({
    id: 30,
    kind: 'expense',
    direction: 'incoming',
    number: '26210-H120-5154',
    source_number: '26210-H120-5154',
    internal_number: 'T-2026-0023',
    partner_name: 'Centar za vozila Hrvatske d.d.',
    ubl_available: true,
    pdf_available: false,
    supplier: {
      id: 26,
      name: 'Centar za vozila Hrvatske d.d.',
      country_code: 'HR',
      address: { street: 'Ćirila i Metoda 11', postal_code: '22211', city: 'Vodice' },
      oib: '73294314024',
      vat_id: 'HR73294314024',
      tax_id: '73294314024',
      primary_iban: null,
    },
    document: {
      issue_date: '2026-08-06',
      delivery_date: '2026-08-06',
      due_date: '2026-08-06',
      received_at: '2026-08-06T17:01:05+02:00',
      currency: 'EUR',
      business_process: 'P5',
      source_label: 'SUPER eRačun',
      format: 'UBL',
      primary_reference: 'HR03 1201-0262102',
    },
    status: {
      document: 'received',
      workflow: 'pending',
      integration: 'received',
      posting: 'unposted',
      vat: 'absent',
      subledger: null,
      payment: null,
    },
    actions: {
      reject: {
        available: false,
        reason_codes: [],
        unavailable_code: 'not_on_gateway',
      },
    },
    accounting: {
      journal_entry_id: null,
      entry_number: null,
      entry_date: null,
      status: 'unposted',
      debit_total: null,
      credit_total: null,
      lines: [],
    },
    vat_context: {
      period: null,
      recorded: false,
      deductible: null,
      total_base: null,
      total_vat: null,
      rates: [],
    },
    subledger_context: {
      item_id: null,
      state: null,
      original_amount: null,
      allocated_amount: null,
      open_amount: null,
      due_date: null,
      allocations: [],
    },
    payment: {
      matched: false,
      date: null,
      amount: null,
      account_mask: null,
      reference: null,
      reconcile_status: null,
      bank_transaction_id: null,
    },
    settlement_trail: {
      obligation: null,
      closings: [],
      system_entries: [],
      warnings: [],
      totals: { obligation: null, allocated: null, open: null },
    },
    lines: [
      {
        position: 1,
        classification: { scheme: 'CG', code: '71.20.04' },
        name: 'Poslovi registracije',
        description: null,
        unit: 'H87',
        quantity: '1',
        unit_price: '7.06',
        vat_rate: '25.00',
        net_amount: '7.06',
        vat_amount: null,
        gross_amount: null,
      },
    ],
    charges: [
      {
        code: '05100',
        type: 'charge',
        description: 'Posebna naknada za okoliš',
        amount: '2.20',
        vat_rate: null,
      },
    ],
    tax_summary: [{ rate: '25.00', base: '29.96', vat: '7.49' }],
    totals: {
      line_net: '29.96',
      charges_total: '334.75',
      allowances_total: null,
      vat_total: '7.49',
      grand_total: '372.20',
      prepaid: '372.20',
      payable: '0.00',
      currency: 'EUR',
    },
    references: [{ type: 'originator', value: 'HR03 1201-0262102' }],
    integration: {
      source: 'super',
      status: 'received',
      received_at: '2026-08-06T17:01:05+02:00',
      external_id: '7a8e295b-5859-4a39-a289-3b92b1ae7469',
      external_view_url: 'https://moj.super.hr/hr/Client/Invoice/ViewDetails/7a8e295b-5859-4a39-a289-3b92b1ae7469',
    },
    technical: {
      message_id: null,
      parser_version: 'ubl.parser.invoice/2',
      imported_at: '2026-08-06T17:01:05+02:00',
      source_hash: null,
    },
    ...overrides,
  });
}
