/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_obtain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/bank-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_bank_accounts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/connections/{id}/sync/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["banking_connections_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/connections/{id}/sync-status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_connections_sync_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_overview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/payment-orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_payment_orders_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/statement-imports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["banking_statement_imports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/statement-imports/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_statement_imports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/statements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_statements_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/statements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_statements_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["banking_transactions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/transactions/{id}/match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["banking_transactions_match"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banking/transactions/{id}/unmatch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["banking_transactions_unmatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{direction}/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{direction}/{id}/pdf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/incoming/{id}/attachments/{attachment_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_attachment_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/partners/{id}/financial-summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finance_partner_financial_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/partners/{id}/subledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finance_partner_subledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET uses read role; mutating methods use write role. */
        get: operations["partners_list"];
        put?: never;
        /** @description GET uses read role; mutating methods use write role. */
        post: operations["partners_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET uses read role; mutating methods use write role. */
        get: operations["partners_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET uses read role; mutating methods use write role. */
        patch: operations["partners_partial_update"];
        trace?: never;
    };
    "/api/partners/{id}/bank-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET uses read role; mutating methods use write role. */
        get: operations["partners_bank_accounts_list"];
        put?: never;
        /** @description GET uses read role; mutating methods use write role. */
        post: operations["partners_bank_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/bank-accounts/{account_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["partners_bank_accounts_destroy"];
        options?: never;
        head?: never;
        patch: operations["partners_bank_accounts_partial_update"];
        trace?: never;
    };
    "/api/partners/{id}/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET uses read role; mutating methods use write role. */
        get: operations["partners_contacts_list"];
        put?: never;
        /** @description GET uses read role; mutating methods use write role. */
        post: operations["partners_contacts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{id}/contacts/{contact_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["partners_contacts_destroy"];
        options?: never;
        head?: never;
        patch: operations["partners_contacts_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Allocation: {
            id: number;
            /** @description Decimal as string, e.g. "1100.00" */
            amount: string;
            created_at: string;
        };
        AmountsBlock: {
            currency: string | null;
            net: string | null;
            vat: string | null;
            gross: string | null;
            fx_rate: components["schemas"]["Provenanced"];
        };
        Attachment: {
            id: number;
            original_filename: string;
            created_at: string | null;
            uploaded_by: string | null;
            download_available: components["schemas"]["Provenanced"];
        };
        AuthMeResponse: {
            user: components["schemas"]["AuthMeUser"];
            tenants: components["schemas"]["AuthMeTenant"][];
            platform_admin_url: string;
        };
        AuthMeTenant: {
            slug: string;
            name: string;
            role: string;
            is_default: boolean;
            admin_url: string;
        };
        AuthMeUser: {
            id: number;
            username: string;
            /** Format: email */
            email: string;
            is_superuser: boolean;
        };
        Balance: {
            balance_type: string;
            /** @description Decimal as string, e.g. "1100.00" */
            amount: string;
            currency: string;
            as_of: string | null;
            source: string;
            is_stale: boolean;
        };
        BankAccount: {
            id: number;
            account_name: string;
            bank_name: string;
            account_number: string;
            iban: string;
            currency: string;
            status: string;
            is_active: boolean;
            connection: components["schemas"]["ConnectionSummary"] | null;
            balances: components["schemas"]["Balance"][];
        };
        BankBlock: {
            match_status: components["schemas"]["Provenanced"];
        };
        BankingOverview: {
            as_of: string;
            accounts: components["schemas"]["BankAccount"][];
            /** @description Per-currency account counts; no cross-currency total balance */
            account_count_by_currency: {
                [key: string]: number;
            };
            unmatched_transaction_count: number;
            suggested_transaction_count: number;
            statement_count: number;
        };
        CodeDetail: {
            code: string;
            detail: string;
        };
        ConnectionSummary: {
            id: number;
            status: string;
            provider_code: string;
            last_sync_at: string | null;
        };
        Contact: {
            id: number;
            partner_id: number;
            contact_type: string;
            first_name: string;
            last_name: string;
            full_name: string;
            position: string;
            department: string;
            email: string;
            phone: string;
            mobile: string;
            notes: string;
            is_primary: boolean;
            is_active: boolean;
            created_at: string | null;
        };
        ContactList: {
            as_of: string;
            count: number;
            results: components["schemas"]["Contact"][];
        };
        ContactWriteRequest: {
            contact_type?: string;
            first_name?: string;
            last_name?: string;
            position?: string;
            department?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            mobile?: string;
            notes?: string;
            is_primary?: boolean;
            is_active?: boolean;
        };
        CurrencySummary: {
            outgoing_count: number;
            incoming_count: number;
            outgoing_gross: string | null;
            incoming_gross: string | null;
            open_receivables: string | null;
            open_payables: string | null;
        };
        /**
         * @description * `incoming` - incoming
         *     * `outgoing` - outgoing
         * @enum {string}
         */
        DirectionEnum: "incoming" | "outgoing";
        DocumentDetail: {
            id: number;
            direction: components["schemas"]["DirectionEnum"];
            internal_number: string | null;
            source_number: string | null;
            partner_name: string | null;
            partner_oib: string | null;
            partner_vat_number: string | null;
            document_date: string | null;
            due_date: string | null;
            document_status: components["schemas"]["Provenanced"];
            operational_status: components["schemas"]["Provenanced"];
            posting: components["schemas"]["PostingBlock"];
            subledger: components["schemas"]["SubledgerBlock"];
            bank: components["schemas"]["BankBlock"];
            payment_order: components["schemas"]["PaymentOrderBlock"];
            vat: components["schemas"]["VatBlock"];
            eracun: components["schemas"]["EracunBlock"];
            fiscal: components["schemas"]["FiscalBlock"];
            controls: string[];
            notices: string[];
            amounts: components["schemas"]["AmountsBlock"];
            partner_id: number | null;
            description: string | null;
            notes: string | null;
            created_at: string | null;
            updated_at: string | null;
            created_by: string | null;
            items: components["schemas"]["DocumentItem"][];
            service_date: string | null;
            journal_lines: components["schemas"]["JournalLine"][];
            payments: components["schemas"]["DocumentPayment"][];
            allocations: components["schemas"]["Allocation"][];
            ledger_entries: components["schemas"]["LedgerEntry"][];
            attachments: components["schemas"]["Attachment"][];
            ubl_available: boolean;
            as_of: string;
        };
        DocumentItem: {
            item_name: string;
            quantity: string;
            unit_price: string;
            tax_rate: string;
            vat_procedure: string | null;
            line_total: string;
        };
        DocumentListSummary: {
            by_currency: {
                [key: string]: components["schemas"]["CurrencySummary"];
            };
        };
        DocumentPayment: {
            id: number;
            payment_number: string;
            /** @description Decimal as string, e.g. "1100.00" */
            amount: string;
            payment_date: string | null;
            payment_method: string;
            status: string;
        };
        DocumentSummary: {
            id: number;
            direction: components["schemas"]["DirectionEnum"];
            internal_number: string | null;
            source_number: string | null;
            partner_name: string | null;
            partner_oib: string | null;
            partner_vat_number: string | null;
            document_date: string | null;
            due_date: string | null;
            document_status: components["schemas"]["Provenanced"];
            operational_status: components["schemas"]["Provenanced"];
            posting: components["schemas"]["PostingBlock"];
            subledger: components["schemas"]["SubledgerBlock"];
            bank: components["schemas"]["BankBlock"];
            payment_order: components["schemas"]["PaymentOrderBlock"];
            vat: components["schemas"]["VatBlock"];
            eracun: components["schemas"]["EracunBlock"];
            fiscal: components["schemas"]["FiscalBlock"];
            controls: string[];
            notices: string[];
            amounts: components["schemas"]["AmountsBlock"];
        };
        EracunBlock: {
            as4_status: components["schemas"]["Provenanced"];
            message_id: components["schemas"]["Provenanced"];
            source: components["schemas"]["Provenanced"];
        };
        /** @description DRF-style error body: ``{"detail": ...}`` where detail may be str or object. */
        ErrorDetail: {
            detail: unknown;
        };
        ExportLimitError: {
            detail: string;
            limit: number;
            count: number;
        };
        FiscalBlock: {
            jir: components["schemas"]["Provenanced"];
            zki: components["schemas"]["Provenanced"];
        };
        ImportRunCreateResponse: {
            id: number;
            run_uuid: string;
            status: string;
            source: string;
            format: string;
            original_filename: string;
            statements_processed: number;
            statements_created: number;
            statements_updated: number;
            transactions_processed: number;
            transactions_created: number;
            transactions_skipped: number;
            error_count: number;
            warnings: string[];
            errors: string[];
            created_at: string | null;
            started_at: string | null;
            finished_at: string | null;
            created: boolean;
        };
        ImportRunDetail: {
            id: number;
            run_uuid: string;
            status: string;
            source: string;
            format: string;
            original_filename: string;
            statements_processed: number;
            statements_created: number;
            statements_updated: number;
            transactions_processed: number;
            transactions_created: number;
            transactions_skipped: number;
            error_count: number;
            warnings: string[];
            errors: string[];
            created_at: string | null;
            started_at: string | null;
            finished_at: string | null;
            as_of: string;
        };
        JournalLine: {
            account_code: string;
            account_name: string;
            /** @description Decimal as string, e.g. "1100.00" */
            debit: string;
            /** @description Decimal as string, e.g. "1100.00" */
            credit: string;
            description: string;
        };
        LedgerEntry: {
            ledger_type: string;
            vat_box: string | null;
            vat_rate: string | null;
            /** @description Decimal as string, e.g. "1100.00" */
            base_amount: string;
            /** @description Decimal as string, e.g. "1100.00" */
            vat_amount: string;
            entry_category: string;
            entry_date: string | null;
            document_number: string;
        };
        MatchRequestRequest: {
            target_type: components["schemas"]["TargetTypeEnum"];
            target_id: number;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedBankAccounts: {
            as_of: string;
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["BankAccount"][];
        };
        PaginatedDocuments: {
            as_of: string;
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["DocumentSummary"][];
            summary: components["schemas"]["DocumentListSummary"];
        };
        PaginatedPartners: {
            as_of: string;
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["PartnerListItem"][];
        };
        PaginatedPaymentOrders: {
            as_of: string;
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["PaymentOrder"][];
        };
        PaginatedStatements: {
            as_of: string;
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["StatementListItem"][];
        };
        PaginatedTransactions: {
            as_of: string;
            count: number;
            page: number;
            page_size: number;
            results: components["schemas"]["Transaction"][];
        };
        Partner: {
            id: number;
            partner_code: string;
            name: string;
            short_name: string;
            partner_type: string;
            status: string;
            tax_number: string;
            vat_number: string;
            registration_number: string;
            address: string;
            city: string;
            postal_code: string;
            country: string;
            email: string;
            phone: string;
            mobile: string;
            fax: string;
            website: string;
            payment_terms: number;
            /** @description Decimal as string, e.g. "1100.00" */
            credit_limit: string;
            /** @description Decimal as string, e.g. "1100.00" */
            discount_percentage: string;
            notes: string;
            internal_notes: string;
            created_at: string | null;
            updated_at: string | null;
        };
        PartnerBankAccount: {
            id: number;
            partner_id: number;
            bank_name: string;
            bic: string;
            iban: string;
            currency: string;
            is_primary: boolean;
            is_active: boolean;
            created_at: string | null;
        };
        PartnerBankAccountList: {
            as_of: string;
            count: number;
            results: components["schemas"]["PartnerBankAccount"][];
        };
        PartnerBankAccountWriteRequest: {
            bank_name?: string;
            bic?: string;
            iban?: string;
            currency?: string;
            is_primary?: boolean;
            is_active?: boolean;
        };
        PartnerConflict: {
            code: string;
            field: string;
        };
        PartnerFinancialSummary: {
            partner_id: number;
            as_of_date: string;
            currency: string;
            /** @description Decimal as string, e.g. "1100.00" */
            receivables_open: string;
            /** @description Decimal as string, e.g. "1100.00" */
            payables_open: string;
            /** @description Decimal as string, e.g. "1100.00" */
            receivables_overdue: string;
            /** @description Decimal as string, e.g. "1100.00" */
            payables_overdue: string;
            /** @description Decimal as string, e.g. "1100.00" */
            net_balance: string;
        };
        PartnerListItem: {
            id: number;
            partner_code: string;
            name: string;
            short_name: string;
            partner_type: string;
            status: string;
            tax_number: string;
            city: string;
            country: string;
            email: string;
            phone: string;
        };
        PartnerSubledgerItem: {
            item_id: number;
            partner_id: number;
            partner_name: string;
            direction: string;
            direction_label: string;
            source_type: string;
            source_id: number;
            source_label: string;
            /** @description Decimal as string, e.g. "1100.00" */
            original_amount: string;
            /** @description Decimal as string, e.g. "1100.00" */
            open_amount: string;
            due_date: string | null;
            days_overdue: number;
            aging_bucket: string;
            status: string;
        };
        PartnerSubledgerList: {
            as_of_date: string;
            partner_id: number;
            count: number;
            results: components["schemas"]["PartnerSubledgerItem"][];
        };
        PartnerWriteRequest: {
            name?: string;
            short_name?: string;
            partner_type?: string;
            status?: string;
            tax_number?: string;
            vat_number?: string;
            registration_number?: string;
            address?: string;
            city?: string;
            postal_code?: string;
            country?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            mobile?: string;
            fax?: string;
            website?: string;
            payment_terms?: number;
            credit_limit?: string;
            discount_percentage?: string;
            notes?: string;
            internal_notes?: string;
        };
        PatchedContactWriteRequest: {
            contact_type?: string;
            first_name?: string;
            last_name?: string;
            position?: string;
            department?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            mobile?: string;
            notes?: string;
            is_primary?: boolean;
            is_active?: boolean;
        };
        PatchedPartnerBankAccountWriteRequest: {
            bank_name?: string;
            bic?: string;
            iban?: string;
            currency?: string;
            is_primary?: boolean;
            is_active?: boolean;
        };
        PatchedPartnerWriteRequest: {
            name?: string;
            short_name?: string;
            partner_type?: string;
            status?: string;
            tax_number?: string;
            vat_number?: string;
            registration_number?: string;
            address?: string;
            city?: string;
            postal_code?: string;
            country?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            mobile?: string;
            fax?: string;
            website?: string;
            payment_terms?: number;
            credit_limit?: string;
            discount_percentage?: string;
            notes?: string;
            internal_notes?: string;
        };
        /** @description Allowlist only — no SCA, tokens, provider secrets, or internal errors. */
        PaymentOrder: {
            id: number;
            status: string;
            /** @description Decimal as string, e.g. "1100.00" */
            amount: string;
            currency: string;
            /** @description Masked IBAN */
            debtor_iban: string;
            /** @description Masked IBAN */
            creditor_iban: string;
            creditor_name: string;
            reference: string;
            created_at: string;
        };
        PaymentOrderBlock: {
            status: components["schemas"]["Provenanced"];
            creditor_iban: components["schemas"]["Provenanced"];
        };
        PeriodReturn: {
            id: number;
            version: number;
            status: string;
            superseded_by_id: number | null;
            submitted_at: string | null;
            has_active_submission_event: boolean;
            submission_nos: string[];
        };
        PostingBlock: {
            state: components["schemas"]["Provenanced"];
            entry_number: components["schemas"]["Provenanced"];
            entry_date: components["schemas"]["Provenanced"];
            fiscal_period: components["schemas"]["Provenanced"];
            fiscal_locked: components["schemas"]["Provenanced"];
        };
        Provenanced: {
            value: unknown;
            reason: (components["schemas"]["ReasonEnum"] | components["schemas"]["NullEnum"]) | null;
            source: string | null;
        };
        /**
         * @description * `not_recorded` - not_recorded
         *     * `not_provable` - not_provable
         *     * `not_applicable` - not_applicable
         * @enum {string}
         */
        ReasonEnum: "not_recorded" | "not_provable" | "not_applicable";
        StatementDetail: {
            id: number;
            statement_number: string;
            bank_account_id: number;
            /** Format: date */
            statement_date: string | null;
            /** @description Decimal as string, e.g. "1100.00" */
            opening_balance: string;
            /** @description Decimal as string, e.g. "1100.00" */
            closing_balance: string;
            status: string;
            currency: string;
            imported_at: string | null;
            reconciled_at: string | null;
            transaction_count: number;
            match_summary: {
                [key: string]: number;
            };
            as_of: string;
        };
        StatementListItem: {
            id: number;
            statement_number: string;
            bank_account_id: number;
            /** Format: date */
            statement_date: string | null;
            /** @description Decimal as string, e.g. "1100.00" */
            opening_balance: string;
            /** @description Decimal as string, e.g. "1100.00" */
            closing_balance: string;
            status: string;
            currency: string;
            imported_at: string | null;
            reconciled_at: string | null;
            transaction_count: number;
        };
        SubledgerBlock: {
            state: components["schemas"]["Provenanced"];
            open_amount: components["schemas"]["Provenanced"];
            original_amount: components["schemas"]["Provenanced"];
            aging_bucket: components["schemas"]["Provenanced"];
            days: components["schemas"]["Provenanced"];
        };
        SyncEnqueueResponse: {
            id: number;
            connection_id: number;
            status: string;
            transactions_created: number;
            transactions_skipped: number;
            last_error: string | null;
            correlation_id: string | null;
            created_at: string | null;
            started_at: string | null;
            finished_at: string | null;
            created: boolean;
            auto_create_payments: boolean;
        };
        SyncRun: {
            id: number;
            connection_id: number;
            status: string;
            transactions_created: number;
            transactions_skipped: number;
            last_error: string | null;
            correlation_id: string | null;
            created_at: string | null;
            started_at: string | null;
            finished_at: string | null;
        };
        SyncStatus: {
            as_of: string;
            connection_id: number;
            connection_status: string;
            last_sync_at: string | null;
            active_sync: components["schemas"]["SyncRun"] | null;
            latest_sync: components["schemas"]["SyncRun"] | null;
        };
        /**
         * @description * `payment` - payment
         *     * `journal_entry` - journal_entry
         * @enum {string}
         */
        TargetTypeEnum: "payment" | "journal_entry";
        TokenObtainRequestRequest: {
            username: string;
            password: string;
            turnstile_token?: string;
        };
        TokenPairResponse: {
            access: string;
            refresh: string;
        };
        TokenRefreshRequestRequest: {
            refresh: string;
        };
        Transaction: {
            id: number;
            bank_statement_id: number;
            bank_account_id: number;
            /** Format: date */
            transaction_date: string | null;
            /** Format: date */
            value_date: string | null;
            /** @description Decimal as string, e.g. "1100.00" */
            amount: string;
            currency: string;
            transaction_type: string;
            description: string;
            reference: string;
            counterparty_name: string;
            counterparty_iban: string;
            external_id: string | null;
            match_status: string;
            matched_payment_id: number | null;
            matched_journal_entry_id: number | null;
        };
        VatBlock: {
            lifecycle: components["schemas"]["Provenanced"];
            ledger_type: components["schemas"]["Provenanced"];
            period: components["schemas"]["Provenanced"];
            boxes: components["schemas"]["Provenanced"];
            document_in_submitted_return: components["schemas"]["Provenanced"];
            period_returns: components["schemas"]["PeriodReturn"][];
            disclaimer: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    auth_token_obtain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainRequestRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    auth_token_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequestRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_bank_accounts_list: {
        parameters: {
            query?: {
                /** @description Page number (min 1, default 1) */
                page?: number;
                /** @description Page size (default 20, max 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBankAccounts"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_connections_sync_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncEnqueueResponse"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_connections_sync_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_overview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankingOverview"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_payment_orders_list: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
                /** @description Page number (min 1, default 1) */
                page?: number;
                /** @description Page size (default 20, max 100) */
                page_size?: number;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaymentOrders"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_statement_imports_create: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRunCreateResponse"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Konflikt (idempotency / match target taken) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Neprocesibilan zahtjev (validacija write operacije) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_statement_imports_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRunDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_statements_list: {
        parameters: {
            query?: {
                bank_account?: number;
                date_from?: string;
                date_to?: string;
                /** @description Page number (min 1, default 1) */
                page?: number;
                /** @description Page size (default 20, max 100) */
                page_size?: number;
                status?: "archived" | "imported" | "reconciled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStatements"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_statements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_transactions_list: {
        parameters: {
            query?: {
                bank_account?: number;
                date_from?: string;
                date_to?: string;
                match_status?: "matched" | "suggested" | "unmatched";
                /** @description Page number (min 1, default 1) */
                page?: number;
                /** @description Page size (default 20, max 100) */
                page_size?: number;
                statement?: number;
                transaction_type?: "credit" | "debit";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactions"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_transactions_match: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MatchRequestRequest"];
                "multipart/form-data": components["schemas"]["MatchRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Konflikt (idempotency / match target taken) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Neprocesibilan zahtjev (validacija write operacije) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    banking_transactions_unmatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Neprocesibilan zahtjev (validacija write operacije) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    documents_list: {
        parameters: {
            query?: {
                amount_max?: number;
                amount_min?: number;
                currency?: string;
                date_from?: string;
                date_to?: string;
                direction?: "incoming" | "outgoing";
                due_from?: string;
                due_to?: string;
                month?: number;
                oib?: string;
                page?: number;
                /** @description Default 20, max 100 */
                page_size?: number;
                /** @description Partner id */
                partner?: number;
                search?: string;
                status?: string;
                view?: "attention" | "bank_unmatched" | "eracun_rejected" | "incoming_ready_to_pay" | "overdue_outgoing" | "partially_paid" | "possible_duplicates" | "unpaid_outgoing" | "unposted" | "vat_mismatch" | "vat_pending";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocuments"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                direction: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    documents_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                direction: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outgoing invoice PDF. Content-Type: application/pdf. Header Content-Disposition: inline; filename="R-....pdf". Incoming direction returns 404. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Invoice PDF unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeDetail"];
                };
            };
        };
    };
    documents_export: {
        parameters: {
            query?: {
                amount_max?: number;
                amount_min?: number;
                currency?: string;
                date_from?: string;
                date_to?: string;
                direction?: "incoming" | "outgoing";
                due_from?: string;
                due_to?: string;
                /** @description Export file type (default csv) */
                format?: "csv" | "xlsx";
                month?: number;
                oib?: string;
                page?: number;
                /** @description Default 20, max 100 */
                page_size?: number;
                /** @description Partner id */
                partner?: number;
                search?: string;
                status?: string;
                view?: "attention" | "bank_unmatched" | "eracun_rejected" | "incoming_ready_to_pay" | "overdue_outgoing" | "partially_paid" | "possible_duplicates" | "unpaid_outgoing" | "unposted" | "vat_mismatch" | "vat_pending";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File download. Content-Type is text/csv; charset=utf-8 or application/vnd.openxmlformats-officedocument.spreadsheetml.sheet. Header Content-Disposition: attachment; filename="documents.csv|xlsx" */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Export limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportLimitError"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    documents_attachment_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes. Content-Type from storage. Header Content-Disposition: inline; filename="<sanitized>". */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Attachment content unavailable */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeDetail"];
                };
            };
        };
    };
    finance_partner_financial_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerFinancialSummary"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    finance_partner_subledger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerSubledgerList"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_list: {
        parameters: {
            query?: {
                /** @description Default active-only; "all" = every status; "inactive" = inactive+blocked */
                filter?: string;
                /** @description Page number (min 1, default 1) */
                page?: number;
                /** @description Page size (default 20, max 100) */
                page_size?: number;
                /** @description customer|supplier|both|other|customers|suppliers */
                partner_type?: string;
                /** @description Search name, code, OIB, VAT */
                search?: string;
                /** @description Exact status filter (overrides default active when set) */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPartners"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PartnerWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PartnerWriteRequest"];
                "multipart/form-data": components["schemas"]["PartnerWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerConflict"];
                };
            };
        };
    };
    partners_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPartnerWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPartnerWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedPartnerWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partner"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerConflict"];
                };
            };
        };
    };
    partners_bank_accounts_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerBankAccountList"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_bank_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PartnerBankAccountWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PartnerBankAccountWriteRequest"];
                "multipart/form-data": components["schemas"]["PartnerBankAccountWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerBankAccount"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerConflict"];
                };
            };
        };
    };
    partners_bank_accounts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_bank_accounts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPartnerBankAccountWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPartnerBankAccountWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedPartnerBankAccountWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerBankAccount"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerConflict"];
                };
            };
        };
    };
    partners_contacts_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactList"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_contacts_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ContactWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ContactWriteRequest"];
                "multipart/form-data": components["schemas"]["ContactWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_contacts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    partners_contacts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedContactWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedContactWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedContactWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Nevaljani upit / ValidationError */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nedostaje ili je nevaljan Bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Nije pronađeno: missing resource, cross-tenant ID, ili autenticiran korisnik bez prava (namjerno 404, ne 403) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
}
